export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const CLEAR_AUTH_STATE = "CLEAR_AUTH_STATE";
export const LOGOUT_USER = "LOGOUT_USER";

export const GET_CONTACTS_REQUEST = "GET_CONTACTS_REQUEST";
export const GET_CONTACTS_SUCCESS = "GET_CONTACTS_SUCCESS";
export const GET_CONTACTS_FAIL = "GET_CONTACTS_FAIL";

export const CREATE_CONTACT_REQUEST = "CREATE_CONTACT_REQUEST";
export const CREATE_CONTACT_SUCCESS = "CREATE_CONTACT_SUCCESS";
export const CREATE_CONTACT_FAIL = "CREATE_CONTACT_FAIL";

export const DELETE_CONTACT_REQUEST = "DELETE_CONTACT_REQUEST";
export const DELETE_CONTACT_SUCCESS = "DELETE_CONTACT_SUCCESS";
export const DELETE_CONTACT_FAIL = "DELETE_CONTACT_FAIL";

export const EDIT_CONTACT_REQUEST = "EDIT_CONTACT_REQUEST";
export const EDIT_CONTACT_SUCCESS = "EDIT_CONTACT_SUCCESS";
export const EDIT_CONTACT_FAIL = "EDIT_CONTACT_FAIL";

//GROUP

export const CREATE_GROUP_REQUEST = "CREATE_GROUP_REQUEST";
export const CREATE_GROUP_SUCCESS = "CREATE_GROUP_SUCCESS";
export const CREATE_GROUP_FAIL = "CREATE_GROUP_FAIL";

export const EDIT_GROUP_REQUEST = "EDIT_GROUP_REQUEST";
export const EDIT_GROUP_SUCCESS = "EDIT_GROUP_SUCCESS";
export const EDIT_GROUP_FAIL = "EDIT_GROUP_FAIL";

export const GET_GROUPS_REQUEST = "GET_GROUPS_REQUEST";
export const GET_GROUPS_SUCCESS = "GET_GROUPS_SUCCESS";
export const GET_GROUPS_FAIL = "GET_GROUPS_FAIL";

export const GET_GROUP_REQUEST = "GET_GROUP_REQUEST";
export const GET_GROUP_SUCCESS = "GET_GROUP_SUCCESS";
export const GET_GROUP_FAIL = "GET_GROUP_FAIL";

export const DELETE_GROUP_REQUEST = "DELETE_GROUP_REQUEST";
export const DELETE_GROUP_SUCCESS = "DELETE_GROUP_SUCCESS";
export const DELETE_GROUP_FAIL = "DELETE_GROUP_FAIL";

//EVENT

export const CREATE_EVENT_REQUEST = "CREATE_EVENT_REQUEST";
export const CREATE_EVENT_SUCCESS = "CREATE_EVENT_SUCCESS";
export const CREATE_EVENT_FAIL = "CREATE_EVENT_FAIL";

export const EDIT_EVENT_REQUEST = "EDIT_EVENT_REQUEST";
export const EDIT_EVENT_SUCCESS = "EDIT_EVENT_SUCCESS";
export const EDIT_EVENT_FAIL = "EDIT_EVENT_FAIL";

export const GET_EVENTS_REQUEST = "GET_EVENTS_REQUEST";
export const GET_EVENTS_SUCCESS = "GET_EVENTS_SUCCESS";
export const GET_EVENTS_FAIL = "GET_EVENTS_FAIL";

export const GET_EVENT_REQUEST = "GET_EVENT_REQUEST";
export const GET_EVENT_SUCCESS = "GET_EVENT_SUCCESS";
export const GET_EVENT_FAIL = "GET_EVENT_FAIL";

export const DELETE_EVENT_REQUEST = "DELETE_EVENT_REQUEST";
export const DELETE_EVENT_SUCCESS = "DELETE_EVENT_SUCCESS";
export const DELETE_EVENT_FAIL = "DELETE_EVENT_FAIL";

// RELATION

export const CREATE_RELATION_REQUEST = "CREATE_RELATION_REQUEST";
export const CREATE_RELATION_SUCCESS = "CREATE_RELATION_SUCCESS";
export const CREATE_RELATION_FAIL = "CREATE_RELATION_FAIL";

export const EDIT_RELATION_REQUEST = "EDIT_RELATION_REQUEST";
export const EDIT_RELATION_SUCCESS = "EDIT_RELATION_SUCCESS";
export const EDIT_RELATION_FAIL = "EDIT_RELATION_FAIL";

export const GET_RELATIONS_REQUEST = "GET_RELATIONS_REQUEST";
export const GET_RELATIONS_SUCCESS = "GET_RELATIONS_SUCCESS";
export const GET_RELATIONS_FAIL = "GET_RELATIONS_FAIL";

export const GET_RELATION_REQUEST = "GET_RELATION_REQUEST";
export const GET_RELATION_SUCCESS = "GET_RELATION_SUCCESS";
export const GET_RELATION_FAIL = "GET_RELATION_FAIL";

export const DELETE_RELATION_REQUEST = "DELETE_RELATION_REQUEST";
export const DELETE_RELATION_SUCCESS = "DELETE_RELATION_SUCCESS";
export const DELETE_RELATION_FAIL = "DELETE_RELATION_FAIL";

// SCHOOL

export const CREATE_SCHOOL_REQUEST = "CREATE_SCHOOL_REQUEST";
export const CREATE_SCHOOL_SUCCESS = "CREATE_SCHOOL_SUCCESS";
export const CREATE_SCHOOL_FAIL = "CREATE_SCHOOL_FAIL";

export const EDIT_SCHOOL_REQUEST = "EDIT_SCHOOL_REQUEST";
export const EDIT_SCHOOL_SUCCESS = "EDIT_SCHOOL_SUCCESS";
export const EDIT_SCHOOL_FAIL = "EDIT_SCHOOL_FAIL";

export const GET_SCHOOLS_REQUEST = "GET_SCHOOLS_REQUEST";
export const GET_SCHOOLS_SUCCESS = "GET_SCHOOLS_SUCCESS";
export const GET_SCHOOLS_FAIL = "GET_SCHOOLS_FAIL";

export const GET_SCHOOL_REQUEST = "GET_SCHOOL_REQUEST";
export const GET_SCHOOL_SUCCESS = "GET_SCHOOL_SUCCESS";
export const GET_SCHOOL_FAIL = "GET_SCHOOL_FAIL";

export const DELETE_SCHOOL_REQUEST = "DELETE_SCHOOL_REQUEST";
export const DELETE_SCHOOL_SUCCESS = "DELETE_SCHOOL_SUCCESS";
export const DELETE_SCHOOL_FAIL = "DELETE_SCHOOL_FAIL";

//WORK
export const GET_WORKS_REQUEST = "GET_WORKS_REQUEST";
export const GET_WORKS_SUCCESS = "GET_WORKS_SUCCESS";
export const GET_WORKS_FAIL = "GET_WORKS_FAIL";

export const GET_WORK_REQUEST = "GET_WORK_REQUEST";
export const GET_WORK_SUCCESS = "GET_WORK_SUCCESS";
export const GET_WORK_FAIL = "GET_WORK_FAIL";

// PLACE

export const GET_PLACES_REQUEST = "GET_PLACES_REQUEST";
export const GET_PLACES_SUCCESS = "GET_PLACES_SUCCESS";
export const GET_PLACES_FAIL = "GET_PLACES_FAIL";

export const GET_PLACE_REQUEST = "GET_PLACE_REQUEST";
export const GET_PLACE_SUCCESS = "GET_PLACE_SUCCESS";
export const GET_PLACE_FAIL = "GET_PLACE_FAIL";

//RELATIONSHIP

export const CREATE_RELATIONSHIP_REQUEST = "CREATE_RELATIONSHIP_REQUEST";
export const CREATE_RELATIONSHIP_SUCCESS = "CREATE_RELATIONSHIP_SUCCESS";
export const CREATE_RELATIONSHIP_FAIL = "CREATE_RELATIONSHIP_FAIL";

export const EDIT_RELATIONSHIP_REQUEST = "EDIT_RELATIONSHIP_REQUEST";
export const EDIT_RELATIONSHIP_SUCCESS = "EDIT_RELATIONSHIP_SUCCESS";
export const EDIT_RELATIONSHIP_FAIL = "EDIT_RELATIONSHIP_FAIL";

export const GET_RELATIONSHIPS_REQUEST = "GET_RELATIONSHIPS_REQUEST";
export const GET_RELATIONSHIPS_SUCCESS = "GET_RELATIONSHIPS_SUCCESS";
export const GET_RELATIONSHIPS_FAIL = "GET_RELATIONSHIPS_FAIL";

export const GET_RELATIONSHIP_REQUEST = "GET_RELATIONSHIP_REQUEST";
export const GET_RELATIONSHIP_SUCCESS = "GET_RELATIONSHIP_SUCCESS";
export const GET_RELATIONSHIP_FAIL = "GET_RELATIONSHIP_FAIL";

export const DELETE_RELATIONSHIP_REQUEST = "DELETE_RELATIONSHIP_REQUEST";
export const DELETE_RELATIONSHIP_SUCCESS = "DELETE_RELATIONSHIP_SUCCESS";
export const DELETE_RELATIONSHIP_FAIL = "DELETE_RELATIONSHIP_FAIL";

//FRIEND

export const CREATE_FRIEND_REQUEST = "CREATE_FRIEND_REQUEST";
export const CREATE_FRIEND_SUCCESS = "CREATE_FRIEND_SUCCESS";
export const CREATE_FRIEND_FAIL = "CREATE_FRIEND_FAIL";

export const EDIT_FRIEND_REQUEST = "EDIT_FRIEND_REQUEST";
export const EDIT_FRIEND_SUCCESS = "EDIT_FRIEND_SUCCESS";
export const EDIT_FRIEND_FAIL = "EDIT_FRIEND_FAIL";

export const GET_FRIENDS_REQUEST = "GET_FRIENDS_REQUEST";
export const GET_FRIENDS_SUCCESS = "GET_FRIENDS_SUCCESS";
export const GET_FRIENDS_FAIL = "GET_FRIENDS_FAIL";

export const GET_FRIEND_BY_CRITERIA_REQUEST = "GET_FRIEND_BY_CRITERIA_REQUEST";
export const GET_FRIEND_BY_CRITERIA_SUCCESS = "GET_FRIEND_BY_CRITERIA_SUCCESS";
export const GET_FRIEND_BY_CRITERIA_FAIL = "GET_FRIEND_BY_CRITERIA_FAIL";

export const DELETE_FRIEND_REQUEST = "DELETE_FRIEND_REQUEST";
export const DELETE_FRIEND_SUCCESS = "DELETE_FRIEND_SUCCESS";
export const DELETE_FRIEND_FAIL = "DELETE_FRIEND_FAIL";

//COMMENT

export const CREATE_COMMENT_REQUEST = "CREATE_COMMENT_REQUEST";
export const CREATE_COMMENT_SUCCESS = "CREATE_COMMENT_SUCCESS";
export const CREATE_COMMENT_FAIL = "CREATE_COMMENT_FAIL";

export const EDIT_COMMENT_REQUEST = "EDIT_COMMENT_REQUEST";
export const EDIT_COMMENT_SUCCESS = "EDIT_COMMENT_SUCCESS";
export const EDIT_COMMENT_FAIL = "EDIT_COMMENT_FAIL";

export const GET_COMMENTS_REQUEST = "GET_COMMENTS_REQUEST";
export const GET_COMMENTS_SUCCESS = "GET_COMMENTS_SUCCESS";
export const GET_COMMENTS_FAIL = "GET_COMMENTS_FAIL";

export const GET_COMMENT_REQUEST = "GET_COMMENT_REQUEST";
export const GET_COMMENT_SUCCESS = "GET_COMMENT_SUCCESS";
export const GET_COMMENT_FAIL = "GET_COMMENT_FAIL";

export const DELETE_COMMENT_REQUEST = "DELETE_COMMENT_REQUEST";
export const DELETE_COMMENT_SUCCESS = "DELETE_COMMENT_SUCCESS";
export const DELETE_COMMENT_FAIL = "DELETE_COMMENT_FAIL";

//POST

export const CREATE_POST_REQUEST = "CREATE_POST_REQUEST";
export const CREATE_POST_SUCCESS = "CREATE_POST_SUCCESS";
export const CREATE_POST_FAIL = "CREATE_POST_FAIL";

export const EDIT_POST_REQUEST = "EDIT_POST_REQUEST";
export const EDIT_POST_SUCCESS = "EDIT_POST_SUCCESS";
export const EDIT_POST_FAIL = "EDIT_POST_FAIL";

export const GET_POSTS_REQUEST = "GET_POSTS_REQUEST";
export const GET_POSTS_SUCCESS = "GET_POSTS_SUCCESS";
export const GET_POSTS_FAIL = "GET_POSTS_FAIL";

export const SET_POST_ON_PAGE_REQUEST = "SET_POST_ON_PAGE_REQUEST";
export const SET_POST_ON_PAGE_SUCCESS = "SET_POST_ON_PAGE_SUCCESS";
export const SET_POST_ON_PAGE_FAIL = "SET_POST_ON_PAGE_FAIL";

export const DELETE_POST_REQUEST = "DELETE_POST_REQUEST";
export const DELETE_POST_SUCCESS = "DELETE_POST_SUCCESS";
export const DELETE_POST_FAIL = "DELETE_POST_FAIL";

// LIKE

export const CREATE_LIKE_REQUEST = "CREATE_LIKE_REQUEST";
export const CREATE_LIKE_SUCCESS = "CREATE_LIKE_SUCCESS";
export const CREATE_LIKE_FAIL = "CREATE_LIKE_FAIL";

export const EDIT_LIKE_REQUEST = "EDIT_LIKE_REQUEST";
export const EDIT_LIKE_SUCCESS = "EDIT_LIKE_SUCCESS";
export const EDIT_LIKE_FAIL = "EDIT_LIKE_FAIL";

export const GET_LIKES_REQUEST = "GET_LIKES_REQUEST";
export const GET_LIKES_SUCCESS = "GET_LIKES_SUCCESS";
export const GET_LIKES_FAIL = "GET_LIKES_FAIL";

export const GET_LIKE_REQUEST = "GET_LIKE_REQUEST";
export const GET_LIKE_SUCCESS = "GET_LIKE_SUCCESS";
export const GET_LIKE_FAIL = "GET_LIKE_FAIL";

export const DELETE_LIKE_REQUEST = "DELETE_LIKE_REQUEST";
export const DELETE_LIKE_SUCCESS = "DELETE_LIKE_SUCCESS";
export const DELETE_LIKE_FAIL = "DELETE_LIKE_FAIL";

// ADVERT

export const CREATE_ADVERT_REQUEST = "CREATE_ADVERT_REQUEST";
export const CREATE_ADVERT_SUCCESS = "CREATE_ADVERT_SUCCESS";
export const CREATE_ADVERT_FAIL = "CREATE_ADVERT_FAIL";

export const EDIT_ADVERT_REQUEST = "EDIT_ADVERT_REQUEST";
export const EDIT_ADVERT_SUCCESS = "EDIT_ADVERT_SUCCESS";
export const EDIT_ADVERT_FAIL = "EDIT_ADVERT_FAIL";

export const GET_ADVERTS_REQUEST = "GET_ADVERTS_REQUEST";
export const GET_ADVERTS_SUCCESS = "GET_ADVERTS_SUCCESS";
export const GET_ADVERTS_FAIL = "GET_ADVERTS_FAIL";

export const GET_ADVERT_REQUEST = "GET_ADVERT_REQUEST";
export const GET_ADVERT_SUCCESS = "GET_ADVERT_SUCCESS";
export const GET_ADVERT_FAIL = "GET_ADVERT_FAIL";

export const GET_ADVERT_BY_CRITERIA_REQUEST = "GET_ADVERT_BY_CRITERIA_REQUEST";
export const GET_ADVERT_BY_CRITERIA_SUCCESS = "GET_ADVERT_BY_CRITERIA_SUCCESS";
export const GET_ADVERT_BY_CRITERIA_FAIL = "GET_ADVERT_BY_CRITERIA_FAIL";

export const DELETE_ADVERT_REQUEST = "DELETE_ADVERT_REQUEST";
export const DELETE_ADVERT_SUCCESS = "DELETE_ADVERT_SUCCESS";
export const DELETE_ADVERT_FAIL = "DELETE_ADVERT_FAIL";

// ORDER

export const CREATE_ORDER_REQUEST = "CREATE_ORDER_REQUEST";
export const CREATE_ORDER_SUCCESS = "CREATE_ORDER_SUCCESS";
export const CREATE_ORDER_FAIL = "CREATE_ORDER_FAIL";

export const EDIT_ORDER_REQUEST = "EDIT_ORDER_REQUEST";
export const EDIT_ORDER_SUCCESS = "EDIT_ORDER_SUCCESS";
export const EDIT_ORDER_FAIL = "EDIT_ORDER_FAIL";

export const GET_ORDERS_REQUEST = "GET_ORDERS_REQUEST";
export const GET_ORDERS_SUCCESS = "GET_ORDERS_SUCCESS";
export const GET_ORDERS_FAIL = "GET_ORDERS_FAIL";

export const GET_ORDER_BY_CRITERIA_REQUEST = "GET_ORDER_BY_CRITERIA_REQUEST";
export const GET_ORDER_BY_CRITERIA_SUCCESS = "GET_ORDER_BY_CRITERIA_SUCCESS";
export const GET_ORDER_BY_CRITERIA_FAIL = "GET_ORDER_BY_CRITERIA_FAIL";

export const DELETE_ORDER_REQUEST = "DELETE_ORDER_REQUEST";
export const DELETE_ORDER_SUCCESS = "DELETE_ORDER_SUCCESS";
export const DELETE_ORDER_FAIL = "DELETE_ORDER_FAIL";

//PAYMENT

export const CREATE_PAYMENT_REQUEST = "CREATE_PAYMENT_REQUEST";
export const CREATE_PAYMENT_SUCCESS = "CREATE_PAYMENT_SUCCESS";
export const CREATE_PAYMENT_FAIL = "CREATE_PAYMENT_FAIL";

export const EDIT_PAYMENT_REQUEST = "EDIT_PAYMENT_REQUEST";
export const EDIT_PAYMENT_SUCCESS = "EDIT_PAYMENT_SUCCESS";
export const EDIT_PAYMENT_FAIL = "EDIT_PAYMENT_FAIL";

export const GET_PAYMENTS_REQUEST = "GET_PAYMENTS_REQUEST";
export const GET_PAYMENTS_SUCCESS = "GET_PAYMENTS_SUCCESS";
export const GET_PAYMENTS_FAIL = "GET_PAYMENTS_FAIL";

export const GET_PAYMENT_BY_CRITERIA_REQUEST =
  "GET_PAYMENT_BY_CRITERIA_REQUEST";
export const GET_PAYMENT_BY_CRITERIA_SUCCESS =
  "GET_PAYMENT_BY_CRITERIA_SUCCESS";
export const GET_PAYMENT_BY_CRITERIA_FAIL = "GET_PAYMENT_BY_CRITERIA_FAIL";

export const DELETE_PAYMENT_REQUEST = "DELETE_PAYMENT_REQUEST";
export const DELETE_PAYMENT_SUCCESS = "DELETE_PAYMENT_SUCCESS";
export const DELETE_PAYMENT_FAIL = "DELETE_PAYMENT_FAIL";

// SUBSCRIPTION

export const CREATE_SUBSCRIBE_REQUEST = "CREATE_SUBSCRIBE_REQUEST";
export const CREATE_SUBSCRIBE_SUCCESS = "CREATE_SUBSCRIBE_SUCCESS";
export const CREATE_SUBSCRIBE_FAIL = "CREATE_SUBSCRIBE_FAIL";

export const EDIT_SUBSCRIBE_REQUEST = "EDIT_SUBSCRIBE_REQUEST";
export const EDIT_SUBSCRIBE_SUCCESS = "EDIT_SUBSCRIBE_SUCCESS";
export const EDIT_SUBSCRIBE_FAIL = "EDIT_SUBSCRIBE_FAIL";

export const GET_SUBSCRIBES_REQUEST = "GET_SUBSCRIBES_REQUEST";
export const GET_SUBSCRIBES_SUCCESS = "GET_SUBSCRIBES_SUCCESS";
export const GET_SUBSCRIBES_FAIL = "GET_SUBSCRIBES_FAIL";

export const GET_SUBSCRIPTION_BY_CRITERIA_REQUEST =
  "GET_SUBSCRIPTION_BY_CRITERIA_REQUEST";
export const GET_SUBSCRIPTION_BY_CRITERIA_SUCCESS =
  "GET_SUBSCRIPTION_BY_CRITERIA_SUCCESS";
export const GET_SUBSCRIPTION_BY_CRITERIA_FAIL =
  "GET_SUBSCRIPTION_BY_CRITERIA_FAIL";

export const DELETE_SUBSCRIBE_REQUEST = "DELETE_SUBSCRIBE_REQUEST";
export const DELETE_SUBSCRIBE_SUCCESS = "DELETE_SUBSCRIBE_SUCCESS";
export const DELETE_SUBSCRIBE_FAIL = "DELETE_SUBSCRIBE_FAIL";

//PROFILE

export const CREATE_PROFILE_REQUEST = "CREATE_PROFILE_REQUEST";
export const CREATE_PROFILE_SUCCESS = "CREATE_PROFILE_SUCCESS";
export const CREATE_PROFILE_FAIL = "CREATE_PROFILE_FAIL";

export const EDIT_PROFILE_REQUEST = "EDIT_PROFILE_REQUEST";
export const EDIT_PROFILE_SUCCESS = "EDIT_PROFILE_SUCCESS";
export const EDIT_PROFILE_FAIL = "EDIT_PROFILE_FAIL";

export const GET_PROFILES_REQUEST = "GET_PROFILES_REQUEST";
export const GET_PROFILES_SUCCESS = "GET_PROFILES_SUCCESS";
export const GET_PROFILES_FAIL = "GET_PROFILES_FAIL";

export const GET_PROFILE_BY_CRITERIA_REQUEST =
  "GET_PROFILE_BY_CRITERIA_REQUEST";
export const GET_PROFILE_BY_CRITERIA_SUCCESS =
  "GET_PROFILE_BY_CRITERIA_SUCCESS";
export const GET_PROFILE_BY_CRITERIA_FAIL = "GET_PROFILE_BY_CRITERIA_FAIL";

export const DELETE_PROFILE_REQUEST = "DELETE_PROFILE_REQUEST";
export const DELETE_PROFILE_SUCCESS = "DELETE_PROFILE_SUCCESS";
export const DELETE_PROFILE_FAIL = "DELETE_PROFILE_FAIL";

//USER SUBSCRIPTION

export const CREATE_USER_SUBSCRIPTION_REQUEST =
  "CREATE_USER_SUBSCRIPTION_REQUEST";
export const CREATE_USER_SUBSCRIPTION_SUCCESS =
  "CREATE_USER_SUBSCRIPTION_SUCCESS";
export const CREATE_USER_SUBSCRIPTION_FAIL = "CREATE_USER_SUBSCRIPTION_FAIL";

export const EDIT_USER_SUBSCRIPTION_REQUEST = "EDIT_USER_SUBSCRIPTION_REQUEST";
export const EDIT_USER_SUBSCRIPTION_SUCCESS = "EDIT_USER_SUBSCRIPTION_SUCCESS";
export const EDIT_USER_SUBSCRIPTION_FAIL = "EDIT_USER_SUBSCRIPTION_FAIL";

export const GET_USER_SUBSCRIPTIONS_REQUEST = "GET_USER_SUBSCRIPTIONS_REQUEST";
export const GET_USER_SUBSCRIPTIONS_SUCCESS = "GET_USER_SUBSCRIPTIONS_SUCCESS";
export const GET_USER_SUBSCRIPTIONS_FAIL = "GET_USER_SUBSCRIPTIONS_FAIL";

export const GET_USER_SUBSCRIPTION_BY_CRITERIA_REQUEST =
  "GET_USER_SUBSCRIPTION_BY_CRITERIA_REQUEST";
export const GET_USER_SUBSCRIPTION_BY_CRITERIA_SUCCESS =
  "GET_USER_SUBSCRIPTION_BY_CRITERIA_SUCCESS";
export const GET_USER_SUBSCRIPTION_BY_CRITERIA_FAIL =
  "GET_USER_SUBSCRIPTION_BY_CRITERIA_FAIL";

export const DELETE_USER_SUBSCRIPTION_REQUEST =
  "DELETE_USER_SUBSCRIPTION_REQUEST";
export const DELETE_USER_SUBSCRIPTION_SUCCESS =
  "DELETE_USER_SUBSCRIPTION_SUCCESS";
export const DELETE_USER_SUBSCRIPTION_FAIL = "DELETE_USER_SUBSCRIPTION_FAIL";

export const UPGRADE_USER_SUBSCRIPTION_REQUEST =
  "UPGRADE_USER_SUBSCRIPTION_REQUEST";
export const UPGRADE_USER_SUBSCRIPTION_SUCCESS =
  "UPGRADE_USER_SUBSCRIPTION_SUCCESS";
export const UPGRADE_USER_SUBSCRIPTION_FAIL = "UPGRADE_USER_SUBSCRIPTION_FAIL";

//User
export const CREATE_USER_REQUEST = "CREATE_USER_REQUEST";
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
export const CREATE_USER_FAIL = "CREATE_USER_FAIL";

export const EDIT_USER_REQUEST = "EDIT_USER_REQUEST";
export const EDIT_USER_SUCCESS = "EDIT_USER_SUCCESS";
export const EDIT_USER_FAIL = "EDIT_USER_FAIL";

export const GET_USERS_REQUEST = "GET_USERS_REQUEST";
export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS";
export const GET_USERS_FAIL = "GET_USERS_FAIL";

export const GET_USER_REQUEST = "GET_USERS_REQUEST";
export const GET_USER_SUCCESS = "GET_USERS_SUCCESS";
export const GET_USER_FAIL = "GET_USERS_FAIL";

export const DELETE_USER_REQUEST = "DELETE_USER_REQUEST";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_FAIL = "DELETE_USER_FAIL";

//COMPANY
export const CREATE_COMPANY_REQUEST = "CREATE_COMPANY_REQUEST";
export const CREATE_COMPANY_SUCCESS = "CREATE_COMPANY_SUCCESS";
export const CREATE_COMPANY_FAIL = "CREATE_COMPANY_FAIL";

export const EDIT_COMPANY_REQUEST = "EDIT_COMPANY_REQUEST";
export const EDIT_COMPANY_SUCCESS = "EDIT_COMPANY_SUCCESS";
export const EDIT_COMPANY_FAIL = "EDIT_COMPANY_FAIL";

export const GET_COMPANYS_REQUEST = "GET_COMPANYS_REQUEST";
export const GET_COMPANYS_SUCCESS = "GET_COMPANYS_SUCCESS";
export const GET_COMPANYS_FAIL = "GET_COMPANYS_FAIL";

export const GET_COMPANY_REQUEST = "GET_COMPANY_REQUEST";
export const GET_COMPANY_SUCCESS = "GET_COMPANY_SUCCESS";
export const GET_COMPANY_FAIL = "GET_COMPANY_FAIL";

export const DELETE_COMPANY_REQUEST = "DELETE_COMPANY_REQUEST";
export const DELETE_COMPANY_SUCCESS = "DELETE_COMPANY_SUCCESS";
export const DELETE_COMPANY_FAIL = "DELETE_COMPANY_FAIL";

//POP UP

export const POP_UP_SHOW = "POP_UP_SHOW";
export const POP_UP_CLOSE = "POP_UP_CLOSE";
